name: Update Submodules

on:
  schedule:
    - cron: '0 12 * * *' # Runs daily at 12 PM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Git config
        run: |
          git config user.name "Mina Karam"
          git config user.email "mina.karam@thirdwayv.com"

      - name: Update submodules
        run: git submodule update --remote

      - name: Commit changes
        run: git commit -m "Update submodules to latest commits" || echo "No changes to commit"

      - name: Push changes
        run: git push
